CREATE TABLE COUSTMER (ProductID INT PRIMARY KEY,
                       ProductName VARCHAR(25),
					   BrandID INT,
					   Category_ID INT,
					   Model_Year INT,
					   ListPrice INT)

INSERT INTO COUSTMER VALUES (11,'Mouse',221,551,2022,300)
INSERT INTO COUSTMER VALUES (12,'Keyboard',222,552,2023,700)
INSERT INTO COUSTMER VALUES (13,'CPU',223,553,2022,1500)
INSERT INTO COUSTMER VALUES (14,'Dekstop',224,554,2020,20000)
INSERT INTO COUSTMER VALUES (15,'Mouse',225,556,2019,500)
INSERT INTO COUSTMER VALUES (16,'Keyboard',226,555,2020,1000)

SELECT * FROM COUSTMER

DECLARE
@ProductName VARCHAR(MAX),
@ProductID INT,
@ListPrice INT

DECLARE CURSOR_CUST CURSOR
FOR SELECT 
ProductName,
ProductID,
ListPrice
FROM COUSTMER
--WHERE ProductID > 13;
--WHERE ProductName = 'KEYBOARD';
WHERE ListPrice > 300;

OPEN CURSOR_CUST

FETCH NEXT FROM CURSOR_CUST INTO 
@ProductName,
@ProductID,
@ListPrice;

WHILE @@FETCH_STATUS = 0
BEGIN
FETCH NEXT FROM CURSOR_CUST INTO 
@ProductName,
@ProductID,
@ListPrice;
--PRINT @ProductName + CAST (@ProductID AS VARCHAR);
PRINT @ProductName + CAST (@ListPrice AS VARCHAR);

END;

CLOSE CURSOR_CUST;

DEALLOCATE CURSOR_CUST;
