CREATE TABLE PPRODUCT(ProductID INT PRIMARY KEY,
                       ProductName VARCHAR(25),
					   BrandID INT,
					   Category_ID INT,
					   Model_Year INT,
					   ListPrice INT)

INSERT INTO PPRODUCT VALUES (11,'Mouse',221,551,2022,300)
INSERT INTO PPRODUCT VALUES (12,'Keyboard',222,552,2023,700)
INSERT INTO PPRODUCT VALUES (13,'CPU',223,553,2022,1500)
INSERT INTO PPRODUCT VALUES (14,'Dekstop',224,554,2020,20000)
INSERT INTO PPRODUCT VALUES (15,'Mouse',225,556,2019,500)
INSERT INTO PPRODUCT VALUES (16,'Keyboard',226,555,2020,1000)

SELECT * FROM PPRODUCT

DECLARE
@ProductName VARCHAR (MAX),
@ListPrice INT;

DECLARE Cursor_PPRODUCT CURSOR
FOR SELECT 
ProductName,
ListPrice
FROM PPRODUCT;



OPEN Cursor_PPRODUCT;
FETCH NEXT FROM Cursor_PPRODUCT INTO
@ProductName,
@ListPrice ;

PRINT @ProductName + CAST (@ListPrice AS VARCHAR);

WHILE @@FETCH_STATUS = 0
BEGIN
FETCH NEXT FROM Cursor_PPRODUCT INTO
@ProductName,
@ListPrice ;
PRINT @ProductName + CAST (@ListPrice AS VARCHAR);
END;

CLOSE Cursor_PPRODUCT;

DEALLOCATE Cursor_PPRODUCT;
