CREATE TABLE TEACHER (ID INT PRIMARY KEY,
                      AGE INT
					  )

INSERT INTO TEACHER VALUES (111,23)
INSERT INTO TEACHER VALUES (112,30)
INSERT INTO TEACHER VALUES (113,25)

CREATE TABLE TEACHER_SUBJECT (ID INT ,
                              SUBJECT VARCHAR(20),
							  CONSTRAINT  T1 FOREIGN KEY (ID)
							  REFERENCES TEACHER (ID)
							 )

INSERT INTO TEACHER_SUBJECT VALUES(111,'CHEMISTRY')
INSERT INTO TEACHER_SUBJECT VALUES(111,'ENGLISH')
INSERT INTO TEACHER_SUBJECT VALUES(112,'MATHS')
INSERT INTO TEACHER_SUBJECT VALUES(113,'BIOLOGY')
INSERT INTO TEACHER_SUBJECT VALUES(113,'COMPUTER')

SELECT * FROM TEACHER
SELECT * FROM TEACHER_SUBJECT